steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA", "."]
    dir: "services/admin-api"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA"]
    dir: "services/admin-api"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "admin-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--vpc-connector"
      - "cloud-run-vpc-connector"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "FRONTEND_HOST=$_FRONTEND_HOST"
    dir: "services/admin-api"
images:
  - "gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA"
