steps:
  - name: "bash"
    args: ["mkdir", "local-packages"]
    dir: "services/admin-api"
  - name: "bash"
    args: ["cp", "-r", "../../packages/faunadb", "local-packages/"]
    dir: "services/admin-api"
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA", "."]
    dir: "services/admin-api"
  - name: "bash"
    args: ["rm", "-fr", "local-packages"]
    dir: "services/admin-api"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA"]
    dir: "services/admin-api"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "admin-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--vpc-connector"
      - "cloud-run-vpc-connector"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "FAUNADB_ADMIN_SECRET=$_FAUNADB_ADMIN_SECRET,FAUNADB_SERVER_SECRET=$_FAUNADB_SERVER_SECRET,MAGIC_SECRET_KEY=$_MAGIC_SECRET_KEY,COOKIE_SECRET=$_COOKIE_SECRET,JWT_SECRET=$_JWT_SECRET"
    dir: "services/admin-api"
images:
  - "gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA"
